version: '3.8'

services:
  rss_sender:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # SQLite database
      - ./src/db:/app/db
      # Configuration files
      - ./src/config:/app/config
