bot_token: '6199544987:AAF55Ka0WtCJRJfPgFLSfAnjn-FMHAdcnwE'

feeds:
  -
    channel_id: '-1001813244503'
    rss_feed_url: 'https://www.lavozdegalicia.es/santiago/index.xml'
  # -
  #   channel_id: '-1001813244503'
  #   rss_feed_url: 'https://www.lavozdegalicia.es/barbanza/index.xml'
  -
    channel_id: '-1001813244503'
    rss_feed_url: 'https://gal.galiciapress.es/feed/all'
  # -
  #   channel_id: '-1001813244503'
  #   rss_feed_url: 'https://cnnespanol.cnn.com/tag/koala/feed/'
  -
    channel_id: '-1001813244503'
    rss_feed_url: 'https://www.eldiario.es/rss/galicia/'
