source 'https://rubygems.org'

# Lectura y procesado de RSS
gem 'rss', '0.3.1'

# Comunicación con Telegram
gem 'telegram-bot-ruby', '2.4'

# BB.DD
gem 'activerecord', '~> 7.2'
gem 'sqlite3', '~> 2.7'

# Parse HTML
gem 'nokogiri', '~> 1.18'
